apiVersion: v1
kind: Service
metadata:
  name: {{ include "vargard.name" . }}-sensor
spec:
  selector:
    app: {{ include "vargard.name" . }}-all
  ports:
    - name: sensor
      port: 8080
      targetPort: 8080
