apiVersion: v1
kind: Service
metadata:
  name: {{ include "vargard.name" . }}-event
spec:
  selector:
    app: {{ include "vargard.name" . }}-all
  ports:
    - name: event
      port: 8082
      targetPort: 8082
