apiVersion: v1
kind: Service
metadata:
  name: {{ include "vargard.name" . }}-inference
spec:
  selector:
    app: {{ include "vargard.name" . }}-all
  ports:
    - name: inference
      port: 8081
      targetPort: 8081
