image:
  sensor:
    repository: vargard/sensor
    tag: latest
  inference:
    repository: vargard/inference
    tag: latest
  event:
    repository: vargard/event
    tag: latest

resources:
  sensor: {}
  inference: {}
  event: {}

mqtt:
  broker: mqtt.example.com
  port: 8883

ros:
  security:
    enabled: false
    enclave: ""
