name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 .
      - name: Type-check with mypy
        run: mypy .
      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q
  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Sensor Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.sensor
          push: false
          tags: vargard/sensor:latest
      - name: Build Inference Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.inference
          push: false
          tags: vargard/inference:latest
      - name: Build Event Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.event
          push: false
          tags: vargard/event:latest